name: classification

on:
  pull_request: 
    branches:
      - master # this can be main
    paths:
      - "classification/**"

jobs:
  classification:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./classification
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Build container
      run: |
        docker build --tag classification:latest .
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Push2ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ap-southeast-1
        image: classification:latest
    - name: Update lambda with image
      run: aws lambda update-function-code --function-name  classification --image-uri 012059564752.dkr.ecr.ap-southeast-1.amazonaws.com/classification:latest
